---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_monitoring:
        enabled: false
      cloud_backup:
        enabled: false
      omnibus_updater:
        enabled: false
        
platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list: recipe[c8::default]
    attributes: {
  "drupal": {
    "db_password": "drupaluser",
    "db_source": "http://5f8981e76f355afba706-4f938954db59b7e824997e62ff19ce4f.r83.cf1.rackcdn.com/drupal.sql",
  }
}