source 'https://rubygems.org'

gem 'berkshelf', '> 3'
gem 'chef', '>= 11.8'
gem 'chef-sugar'
gem 'chefspec', '>= 3.4'
gem 'foodcritic', '>= 3.0'
gem 'guard', '>= 2.6'
gem 'guard-foodcritic', '>= 1.0.2'
gem 'guard-rubocop', '>= 1.1'
gem 'kitchen-vagrant'
gem 'rake', '>= 10.2'
gem 'rubocop', '= 0.23'
gem 'serverspec', '>= 1.6'
gem 'test-kitchen'
gem 'vagrant-wrapper'
